### ISSUE TITLE
BAD signature for TWRP 3.7.0 dreamlte

### ISSUE THREAD

**Issue by i-can-not-program** [TeamWin/twrpme#149]
When trying to verify `twrp-3.7.0_9-0-dreamlte.img` downloaded from https://dl.twrp.me/ with `$ gpg verify twrp-3.7.0_9-0-dreamlte.img.asc` it says:
```
gpg: Signature made Tue 11 Oct 2022 13:48:09 NZDT
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
```

It doesn't happen for 3.6.2:
```
$ gpg --verify twrp-3.6.2_9-0-dreamlte.img.asc
gpg: assuming signed data in 'twrp-3.6.2_9-0-dreamlte.img'
gpg: Signature made Fri 10 Jun 2022 11:24:23 NZST
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
```

And I verified the SHA256:
```
$ sha256sum -c twrp-3.7.0_9-0-dreamlte.img.sha256
twrp-3.7.0_9-0-dreamlte.img: OK
$ sha256sum -c twrp-3.6.2_9-0-dreamlte.img.sha256
twrp-3.6.2_9-0-dreamlte.img: OK
```

**Comment by bigbiff** [comment]
Thanks for the report. This issue is now corrected. 

jenkins@ns103310:/www/dl.twrp.me/dreamlte$ gpg --verify twrp-3.7.0_9-0-dreamlte.img.asc
gpg: assuming signed data in 'twrp-3.7.0_9-0-dreamlte.img'
gpg: Signature made Fri 20 Jan 2023 03:08:22 AM UTC
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
