### ISSUE TITLE
wget fails without error

### ISSUE THREAD

**Issue by iamfionn** [TeamWin/twrpme#28]
Downloading images with wget fails without error.
```
$ wget https://dl.twrp.me/crackling/twrp-3.0.3-0-crackling.img
--2017-02-06 01:53:21--  https://dl.twrp.me/crackling/twrp-3.0.3-0-crackling.img
Resolving dl.twrp.me (dl.twrp.me)... 198.27.116.169
Connecting to dl.twrp.me (dl.twrp.me)|198.27.116.169|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7283 (7.1K) [text/html]
Saving to: ‘twrp-3.0.3-0-crackling.img’

twrp-3.0.3-0-crackling.img      100%[===========================>]  7.11K  --.-KB/s  in 0s

2017-02-06 01:53:21 (847 MB/s) - ‘twrp-3.0.3-0-crackling.img’ saved [7283/7283]

$ gpg --verify twrp-3.0.3-0-crackling.img.asc 
gpg: assuming signed data in 'twrp-3.0.3-0-crackling.img'
gpg: Signature made Thu 19 Jan 2017 13:14:41 GMT
gpg:                using RSA key 1D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
```
Instead it downloads the download page. This seems dangerous: a user who doesn't verify the integrity of their download would flash this file to their device.

Additionally, the `.asc` extension on the signature file suggests that it is ASCII-armoured, but it isn't.

**Comment by Treora** [comment]
Was about to file the same issue, but then found this one. Will copy my explanation here for in case it adds information.

### Image download URL returns html page

**Observation:** Unless the right `Referer` header is set, resolving e.g. `https://eu.dl.twrp.me/i9100/twrp-3.1.0-0-i9100.img` returns the content of the download info page (`https://eu.dl.twrp.me/i9100/twrp-3.1.0-0-i9100.img.html`), instead of the image file itself.

**Problem:** This breaks many ways people may use to download the file. E.g. when using `wget`, one ends up with the html page rather than the actual image file (and heimdall will happily write that page to your device..).

**Workaround:** To download images from command line or in a script:
`wget --header "Referer: https://eu.dl.twrp.me" https://eu.dl.twrp.me/i9100/twrp-3.1.0-0-i9100.img` (or likewise for other mirrors and URLs)

**Solution:** Have the image url always return the image.

**Comment by bigbiff** [comment]
We require a browser to download images.
